### ISSUE TITLE
Invalid time control message

### ISSUE THREAD

**Issue by GrahamCCRL** [sroelants/simbelmyne#168]
Engine crashes with that message.
I'm using 12 minutes with 8 second (8000ms) increments.

**Comment by sroelants** [comment]
For posterity:

There were two issues going on at once here:
1. The matches were crashing because of the stack overflowing on Windows (stack sizes are 1mb, vs 8mb on Linux). Fixed in bf277a84b063ce670ddd53cc688d76361eb98796.
2. When testing manually by running a simple `go` command, the engine rejected the command. I _think_ the UCI spec doesn't actually define what `go` by itself should do, but Stockfish seems to default to `go infinite`, so that's what we'll do. Fixed in 9cc53b56524cd1b93564f36836983604c2b98906
