### ISSUE TITLE
Hash size

### ISSUE THREAD

**Issue by SzotsGabor** [sroelants/simbelmyne#170]
I set hash to 256 MB under Arena but it seems the engine uses only 64 MB anyway. It's OK from the command line though.

BTW, initialization takes about 20 seconds.

EDIT: Stopped then resumed tournament and now hash size is OK.

Oh no, after a couple of moves it is back to 64 MB again!

**Comment by sroelants** [comment]
Oh dear! It turns out I'm resetting the hash size back to 64mb after every game! 🤦.

Can you say a bit more about the initialization, though? I don't seem to have any noticeable initialization time.

I can release a bugfix for the hash size later today. Up to you whether you want to continue using the engine as-is, or have a more reliable result with a non-broken hash-size. 😄

**Comment by sroelants** [comment]
Thanks! I'll try playing around with Arena as well to see why it takes so long!

**Comment by sroelants** [comment]
Both issues (the hash-size resetting to 64mb and the 20s delay when starting the engine) are both resolved in [v1.5.1](https://github.com/sroelants/simbelmyne/releases/tag/v1.5.1) Nothing else was changed, so the engine is functionally the same.
